name-template: "v$NEXT_PATCH_VERSION 🌟"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "ci"
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
no-changes-template: "📭 No changes in this release."

template: |
  ## What's Changed
  $CHANGES

  👀 Full Changelog: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$CURRENT_TAG
