name: Version Bump on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Get released version
        id: get_version
        run: |
          echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Calculate next patch version
        id: bump_version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          jq --arg ver "$NEXT_VERSION" '.version = $ver' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Commit and push version bump
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: bump version to ${{ env.NEXT_VERSION }} after release [skip ci]"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          branch: main

